name: movecare
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gallery_image_viewer: ^1.2.0
  google_fonts: ^6.1.0
  flutter_modular: ^6.3.2
  intersperse: ^2.0.0
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5


# flutter_native_splash:
#   color: "#ffffff"
#   image: "assets/launcher_icon/icon_splash.png"
#   android: true
#   ios: true
#   android_12: 
#     image: "assets/launcher_icon/icon_splash_android12.png"

# flutter_launcher_icons:
#   image_path: "assets/launcher_icon/icon.png"
#   adaptive_icon_foreground: "assets/launcher_icon/icon.png"
#   adaptive_icon_background: "assets/launcher_icon/bg_icon.png"
#   android: true
#   ios: true
#   remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/